# Practice 1

## Instructions

You're going to practice working in pandas. 


You'll walk through instantiating a `DataFrame`, reading data into it, looking at and examining that data, and then playing with it. 


A dataset on the [quality of red wines](https://archive.ics.uci.edu/ml/datasets/wine+quality) is used for this purpose.
It is located in the `data` folder within this directory. It's called `winequality-red.csv`. 


Typically, we use Jupyter notebooks like this for a very specific set of things - presentations and EDA. 


Today, as we'll be playing around with `pandas`, much of what we'll be doing is considered EDA. Therefore, by using a notebook, we'll get a tighter feedback loop with our work than we would trying to write a script. But, in general, **we do not use Jupyter notebooks for development**. 

Below, we've put a set of questions and then a cell for you to work on answers. However, feel free to add additional cells if you'd like. Often it will make sense to use more than one cell for your answers.

## Assignment Questions

### Part 1 - The Basics of DataFrames

Let's start off by following the general workflow that we use when moving data into a DataFrame: 

    * Importing pandas
    * Reading data into the DataFrame
    * Getting a general sense of the data

So, in terms of what you should do for this part...

1. Import pandas

In [1]:
import pandas as pd

2. Read the wine data into a DataFrame.

In [7]:
df = pd.read_csv("data/winequality-red.csv",sep=";")

3. Use the `attributes` and `methods` available on DataFrames to answer the following questions: 
    * How many rows and columns are in the DataFrame?
    * What data type is in each column?
    * Are all of the variables continuous, or are any categorical?
    * How many non-null values are in each column?
    * What are the min, mean, max, median for all numeric columns?

In [10]:
df.info()
print(df.describe())
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB
       fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000
mean        8.319637          0.527821     0.270976        2.538806
std         1.741096          0.179060     0.194801        1.409928
min         4.600000          0.120000     0.000000        0.900000
25%         7.100000          0.390000     0.090000        1.900000
50%         7.900000          0.520000     0.260000        2.200000
75%         9.200000          0.640000     0.420000        2.600000
max        15.900000          1.580000     1.000000       15.500000

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000
mean      0.087467            15.874922             46.467792     0.996747
std       0.047065            10.460157             32.895324     0.001887
min       0.012000             1.000000              6.000000     0.990070
25%       0.070000             7.000000             22.000000     0.995600
50%       0.079000            14.000000             38.000000     0.996750
75%       0.090000            21.000000             62.000000     0.997835
max       0.611000            72.000000            289.000000     1.003690

                pH    sulphates      alcohol      quality
count  1599.000000  1599.000000  1599.000000  1599.000000
mean      3.311113     0.658149    10.422983     5.636023
std       0.154386     0.169507     1.065668     0.807569
min       2.740000     0.330000     8.400000     3.000000
25%       3.210000     0.550000     9.500000     5.000000
50%       3.310000     0.620000    10.200000     6.000000
75%       3.400000     0.730000    11.100000     6.000000
max       4.010000     2.000000    14.900000     8.000000

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

### Part 2 - Practice with Grabbing Data

Let's now get some practice with grabbing certain parts of the data. If you'd like some extra practice, try answering each of the questions in more than one way (because remember, we can often grab our data in a couple of different ways).

1. Grab the first 10 rows of the `chlorides` column.

In [17]:
df.chlorides[0:9]

0    0.076
1    0.098
2    0.092
3    0.075
4    0.076
5    0.075
6    0.069
7    0.065
8    0.073
Name: chlorides, dtype: float64

2. Grab the last 10 rows of the `chlorides` column.

In [23]:
df.chlorides[-10:]

1589    0.073
1590    0.077
1591    0.089
1592    0.076
1593    0.068
1594    0.090
1595    0.062
1596    0.076
1597    0.075
1598    0.067
Name: chlorides, dtype: float64

3. Grab indices 264-282 of the `chlorides` **and** `density` columns.

In [30]:
df[['chlorides', 'density']][264:282]

     chlorides  density
264      0.064  0.99990
265      0.071  0.99680
266      0.096  1.00025
267      0.078  0.99730
268      0.077  0.99870
269      0.104  0.99960
270      0.087  0.99650
271      0.104  0.99960
272      0.071  0.99935
273      0.076  0.99735
274      0.088  0.99915
275      0.087  0.99650
276      0.077  0.99870
277      0.104  0.99960
278      0.073  0.99760
279      0.087  0.99910
280      0.071  0.99860
281      0.358  0.99720

4. Grab all rows where the `chlorides` value is less than 0.10.

In [34]:
df['chlorides'][df['chlorides']<0.10]

0       0.076
1       0.098
2       0.092
3       0.075
4       0.076
        ...
1594    0.090
1595    0.062
1596    0.076
1597    0.075
1598    0.067
Name: chlorides, Length: 1363, dtype: float64

5. Now grab all the rows where the `chlorides` value is greater than the column's mean (try **not** to use a hard-coded value for the mean, but instead a method).

In [ ]:
df['chlorides'][df['chlorides'] < df['chlorides'].mean()]

0       0.076
3       0.075
4       0.076
5       0.075
6       0.069
        ...
1593    0.068
1595    0.062
1596    0.076
1597    0.075
1598    0.067
Name: chlorides, Length: 1125, dtype: float64

6. Grab all those rows where the `pH` is greater than 3.0 and less than 3.5.

In [41]:
df[(df['pH']<3.5) & (df['pH']>3.0)]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0,7
...,...,...,...,...,...,...,...,...,...,...,...,...
1592,6.3,0.51,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1593,6.8,0.62,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
1594,6.2,0.60,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1596,6.3,0.51,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1598,6.0,0.31,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6


7. Further filter the results from 6 to grab only those rows that have a `residual sugar` less than 2.0.

In [42]:
df[(df['pH']<3.5) & (df['pH']>3.0) & (df['residual sugar']<=2.0)]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0,7
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.99680,3.36,0.57,9.5,7
10,6.7,0.58,0.08,1.8,0.097,15.0,65.0,0.99590,3.28,0.54,9.2,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1576,8.0,0.30,0.63,1.6,0.081,16.0,29.0,0.99588,3.30,0.78,10.8,6
1578,6.8,0.67,0.15,1.8,0.118,13.0,20.0,0.99540,3.42,0.67,11.3,6
1590,6.3,0.55,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,6
1593,6.8,0.62,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
1594,6.2,0.60,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5

In [48]:
# make a copy of your DataFrame
df2 = df.copy()
# make a list column names
cols = df2.columns.tolist()
# replace space with _
cols = [col.replace(' ', '_') for col in cols]
# reassign new column names to DataFrame
df2.columns = cols
print(df2.columns)
df2.query('3.0 < pH < 3.5 and residual_sugar <= 2.0')

Index(['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
       'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='str')

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0,7
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.99680,3.36,0.57,9.5,7
10,6.7,0.58,0.08,1.8,0.097,15.0,65.0,0.99590,3.28,0.54,9.2,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1576,8.0,0.30,0.63,1.6,0.081,16.0,29.0,0.99588,3.30,0.78,10.8,6
1578,6.8,0.67,0.15,1.8,0.118,13.0,20.0,0.99540,3.42,0.67,11.3,6
1590,6.3,0.55,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,6
1593,6.8,0.62,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
1594,6.2,0.60,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5

### Part 3 - More Practice

Let's move on to some more complicated things. Use your knowledge of `groupby`s, `sorting` to answer the following.

1. Get the average amount of `chlorides` for each `quality` value.

In [55]:
df[['quality','chlorides']].groupby('quality').mean().sort_values('quality')

         chlorides
quality
3         0.122500
4         0.090679
5         0.092736
6         0.084956
7         0.076588
8         0.068444

 2. For observations with a `pH` greater than 3.0 and less than 4.0, find the average `alcohol` value by `pH`.

In [60]:
df2[['pH','alcohol']].query('3.0 < pH < 3.5').groupby('pH').mean()

        alcohol
pH
3.01  11.320000
3.02  10.200000
3.03   9.633333
3.04   9.740000
3.05  10.050000
3.06  10.470000
3.07  10.278788
3.08   9.527273
3.09  10.154545
3.10   9.915789
3.11  10.555556
3.12  10.055000
3.13   9.946154
3.14  10.447619
3.15  10.308824
3.16   9.904630
3.17  10.244444
3.18  10.533333
3.19   9.988000
3.20  10.256410
3.21  10.452778
3.22  10.694872
3.23  10.684375
3.24  10.372414
3.25  10.023077
3.26  10.275472
3.27  10.694286
3.28  10.269048
3.29  10.095652
3.30  10.438596
3.31  10.187179
3.32  10.341481
3.33  10.759459
3.34  10.220930
3.35  10.700000
3.36  10.351786
3.37  10.235135
3.38  10.568750
3.39  10.378125
3.40  10.408108
3.41  10.641176
3.42  10.466667
3.43  10.317647
3.44  10.529310
3.45  10.600000
3.46  10.372727
3.47  10.247619
3.48  10.136842
3.49  10.890000

3. For observations with an `alcohol` value between 9.25 and 9.5, find the highest amount of `residual sugar`.

In [ ]:
df2[['alcohol','residual_sugar']].query('9.25 < alcohol < 9.5').max()

alcohol            9.4
residual_sugar    10.7
dtype: float64

4. Create a new column, called `total_acidity`, that is the sum of `fixed acidity` and `volatile acidity`.

In [65]:
df2['total_acidity']=df2['fixed_acidity']+df2['volatile_acidity']

5. Find the average `total_acidity` for each of the `quality` values.

In [71]:
df2.groupby('quality').mean()[['total_acidity']]

         total_acidity
quality
3             9.244500
4             8.473208
5             8.744295
6             8.844663
7             9.276281
8             8.990000

6. Find the top 5 `density` values.

In [77]:
df2[['density']].sort_values('density').tail(5)

      density
557   1.00315
555   1.00315
442   1.00320
1435  1.00369
1434  1.00369

7. Find the 10 lowest `sulphates` values.

In [78]:
df2[['sulphates']].sort_values('sulphates').head(10)

      sulphates
170        0.33
1369       0.37
1287       0.37
65         0.39
1348       0.39
837        0.39
836        0.39
64         0.39
1347       0.39
1299       0.40